### ISSUE TITLE
Looking for additional maintainers

### ISSUE THREAD

**Issue by kreczko** [HEP-Puppet/htcondor#117]
Since I have very limited time on my hands, definitely not enough to properly look after the HEP-Puppet projects, I am looking for additional helpers.

The discussion started in https://github.com/HEP-Puppet/htcondor/pull/106 and @olifre agreed to help out.

Based on the most recent and frequent contributors @ccnifo would be another one to consider.

@ccnifo Would you be interested to join the club?
It would mostly consist of:
 - reviewing & merging the PRs of others
 - creating new releases

**Comment by kreczko** [comment]
@olifre you should have an invite

**Comment by olifre** [comment]
@kreczko The invite arrived and I accepted just now :wink:.

**Comment by ccnifo** [comment]
@kreczko: that would be new to me, but it sounds doable, especially as I wouldn't be alone for this, just like @olifre pointed in #106 !

**Comment by kreczko** [comment]
Awesome. Thank you very much! Sending invite & closing issue
