### ISSUE TITLE
Add general knob turning

### ISSUE THREAD

**Issue by kreczko** [HEP-Puppet/htcondor#57]
HTCondor has many parameters and they cannot be mapped 1:1 in the puppet module.
My suggestions would be to replace `custom_attribute` with something like a `knobs` array or hash that will create entries in `/etc/condor/conf.d/00_local` (see #56).

**Comment by ccnifo** [comment]
If I understood what youdescribe, it could be an array or a hash, sent to a create_resource, which would create a file_line for each entry?

**Comment by ccnifo** [comment]
Can it be this kind of logic, with a simple hash and no checks? https://github.com/HEP-Puppet/htcondor/blob/0f64542c5afc0eead8c490835b2775dbbd7fab62/templates/14_logging.config.erb

**Comment by kreczko** [comment]
@ccnifo Apologies for the delayed reply - it's conference season.
Yes, a simple hash could be a good first implementation for this.
Should go into a separate config file so users are aware of the special case (anything goes).
