### ISSUE TITLE
healhcheck script mode

### ISSUE THREAD

**Issue by afortiorama** [HEP-Puppet/htcondor#77]
Hi,

the healhcheck script is copied with permission 655 and when condor tries to execute it it fails with permission denied. 

_09/27/17 16:59:16 Create_Process: Cannot access specified executable "/usr/local/bin/healhcheck_wn_condor": errno = 13 (Permission denied)
09/27/17 16:59:16 CronJob: Error running job 'WN_HEALTHCHECK'_

I've fixed it in my fork.

https://github.com/afortiorama/htcondor/blob/master/manifests/config/worker.pp

**Comment by afortiorama** [comment]
I tried to push the change in the development branch but I'm not authorized.

**Comment by kreczko** [comment]
Hi @afortiorama ,

Thanks for the issue and solution. Please make a pull request.
