### ISSUE TITLE
CGROUPS setup in 20_workernode.config.erb

### ISSUE THREAD

**Issue by afortiorama** [HEP-Puppet/htcondor#78]
Hi,

ther is a problem in the worker node template. The line

CGROUP_MEMORY_LIMIT = soft

should be replaced with 

CGROUP_MEMORY_LIMIT_POLICY = soft

as it is htcondor isn't setting  the limits in cgroups when it creates the processes groups and the kernel is letting jobs run wild.

**Comment by kreczko** [comment]
Thanks for spotting this, I will see to it shortly.

**Comment by kreczko** [comment]
Should be fixed in version 2.0.3
