### ISSUE TITLE
Badly initialized variables

### ISSUE THREAD

**Issue by ccnifo** [HEP-Puppet/htcondor#79]
Hello,

The two following variable declarations caused failures to my testing deployment:

https://github.com/HEP-Puppet/htcondor/blob/46f498f75c4eed3935eb8d7cec672bfc5cc3da4a/manifests/init.pp#L138
https://github.com/HEP-Puppet/htcondor/blob/46f498f75c4eed3935eb8d7cec672bfc5cc3da4a/manifests/init.pp#L139

They are initialized using an unexisting value and thus produce the following fatal errors:
`Error 500 on SERVER: Server Error: Evaluation Error: Unknown variable: 'htcondor::params::certificate_mapfile'.`
`Error 500 on SERVER: Server Error: Evaluation Error: Unknown variable: 'htcondor::params::kerberos_mapfile'`

Regarding that I cannot find a single place where they are used, it looks to me that they shouldn't exist. I can open a PR to delete them, hope I did not misunderstood something.

**Comment by kreczko** [comment]
Hi @ccnifo,
Indeed, `certificate_mapfile` should be `cert_map_file` and `kerberos_mapfile` should be `krb_map_file`.
Both of them are used in `security.pp` and both are defined in `init.pp`.

Thus both `certificate_mapfile` and `kerberos_mapfile` can be deleted, thanks for spotting this!

**Comment by ccnifo** [comment]
Thank you! Solved in 2.0.3
